apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-fsx-ontap-nas
spec:
  version: 1
  backendName: fsx-ontap
  storageDriverName: ontap-nas
  managementLIF: management.fs-0d0e948a8bcf2a28a.fsx.us-east-1.amazonaws.com
  dataLIF: svm-0fb4b5f9c6fe55ec4.fs-0d0e948a8bcf2a28a.fsx.us-east-1.amazonaws.com
  svm: svm1
  credentials:
    name: backend-fsx-ontap-nas-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-fsx-ontap-nas-secret
type: Opaque
stringData:
  username: fsxadmin
  password: Master123
